

[package]
name = "ping_pong"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
rppal = "0.22.1"
#tokio = "1.45.1"
tokio = { version = "1.45.1", features = ["full"] }

[features]
client = []
server = []


[[bin]]
name = "echo"
path = "src/echo.rs"

[[bin]]
name = "master"
path = "src/master.rs"
